# Generated by Django 3.2 on 2022-02-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_password_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='username',
            field=models.CharField(default='noname', max_length=20),
        ),
    ]
