# Generated by Django 3.2 on 2022-02-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_password_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='fkey',
            field=models.CharField(default='0', max_length=500),
        ),
    ]
