# Generated by Django 3.2 on 2022-02-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_password_fkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='fkey',
            field=models.BinaryField(),
        ),
    ]
