# Generated by Django 3.2 on 2022-02-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_password_fkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.BinaryField(),
        ),
    ]
